services:
  bugtracker.api:
    image: ${DOCKER_REGISTRY-}bugtrackerapi
    container_name: bugtracker.api
    build:
      context: .
      dockerfile: BugTracker.Api/Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - bugtracker.db

  bugtracker.db:
    image: postgres:latest
    container_name: bugtracker.database
    environment:
        - POSTGRES_DB=bugtracker
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes:
        - ./postgres/bugtracker-db:/var/postresql/data
        - ./BugTracker.Api/BugTrackerDBInitData.sql:/docker-entrypoint-initdb.d/BugTrackerDBInitData.sql
        - ./BugTracker.Api/BugTrackerDBIdentityInitData.sql:/docker-entrypoint-initdb.d/BugTrackerDBIdentityInitData.sql
 
  bugtracker.blazor:
    container_name: bugtracker.blazorui
    build:
        context: ./BugTracker.BlazorUI
        dockerfile: Dockerfile
    ports:
       - 5003:5003
