services:
  bugtracker_api:
    container_name: bugtracker_api
    build:
      context: ./
      dockerfile: ./Bugtracker.Api/Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - bugtracker_db
        - bugtracker_identity.db

  bugtracker_blazor:
    container_name: bugtracker_blazorui
    build:
        context: ./BugTracker.BlazorUI
        dockerfile: ./Dockerfile
    ports:
       - 5003:5003 

  bugtracker_db:
    image: postgres:latest
    container_name: bugtracker_db
    environment:
        - POSTGRES_DB=bugtracker_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes:
        - bt-db-volume:/var/lib/postgresql/data
        - ./BugTracker.Api/BugTrackerDBInitData.sql:/docker-entrypoint-initdb.d/BugTrackerDBInitData.sql
        
  bugtracker_identity_db:
    image: postgres:latest
    container_name: bugtracker_identity_db
    environment:
        - POSTGRES_DB=bugtracker_identity_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5433:5432
    volumes:
        - bt-identity-db-volume:/var/lib/postgresql/data
        - ./BugTracker.Api/BugTrackerDBIdentityInitData.sql:/docker-entrypoint-initdb.d/BugTrackerDBIdentityInitData.sql
  
volumes:
    bt-db-volume:
        name: "bt-db-volume"

    bt-identity-db-volume:
        name: "bt-identity-db-volume"

