services:
  bugtracker.api:
    container_name: bugtracker.api
    build:
      context: ./
      dockerfile: ./Bugtracker.Api/Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - bugtracker.db
        - bugtracker.identity.db

  bugtracker.blazor:
    container_name: bugtracker.blazorui
    build:
        context: ./BugTracker.BlazorUI
        dockerfile: ./Dockerfile
    ports:
       - 5003:5003 

  bugtracker.db:
    image: postgres:latest
    container_name: bugtracker.db
    environment:
        - POSTGRES_DB=bugtracker
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes:
        - bt-db-volume:/var/lib/postgresql/data
        - ./BugTracker.Api/BugTrackerDBInitData.sql:/docker-entrypoint-initdb.d/BugTrackerDBInitData.sql
        
  bugtracker.identity.db:
    image: postgres:latest
    container_name: bugtracker.identity.db
    environment:
        - POSTGRES_DB=bugtracker.identity
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5433:5432
    volumes:
        - bt-identity-db-volume:/var/lib/postgresql/data
        - ./BugTracker.Api/BugTrackerDBIdentityInitData.sql:/docker-entrypoint-initdb.d/BugTrackerDBIdentityInitData.sql
  
volumes:
    bt-db-volume:
        name: "bt-db-volume"

    bt-identity-db-volume:
        name: "bt-identity-db-volume"

